//
//  Localizationmanager.swift
//  smart calculator
//
//  Created by Hevin Technoweb on 09/02/26.
//

import SwiftUI
import Combine

// Language Manager
class LocalizationManager: ObservableObject {
    @Published var currentLanguage: Language = .english {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "selectedLanguage")
        }
    }
    
    init() {
        // Load saved language
        if let savedLanguage = UserDefaults.standard.string(forKey: "selectedLanguage"),
           let language = Language(rawValue: savedLanguage) {
            self.currentLanguage = language
        }
    }
    
    func translate(_ key: String) -> String {
        return currentLanguage.translations[key] ?? key
    }
}

// Supported Languages
enum Language: String, CaseIterable {
    case english = "en"
    case spanish = "sp"
    case french = "fr"
    case portuguese = "pt"
    case russian = "ru"
    case Korean = "ko"
    case German = "de"
    case Italian = "it"
    case Japanese = "ja"
    case hindi = "hi"
    case Indonesian = "id"
    case Chinese = "zh"
    
    var displayName: String {
        switch self {
        case .english: return "English"
        case .spanish: return "Spanish"
        case .french: return "French"
        case .portuguese: return "Portuguese"
        case .russian: return "Russian"
        case .Korean: return "Korean"
        case .German: return "German"
        case .Italian: return "Italian"
        case .Japanese: return "Japanese"
        case .Indonesian: return "Indonesian"
        case .Chinese: return "Chinese"
        case .hindi: return "हिन्दी"
        }
    }
    
    var nativeDisplayName: String {
        switch self {
        case .english: return "English"
        case .spanish: return "Española"
        case .french: return "Français"
        case .portuguese: return "Português"
        case .russian: return "Русский"
        case .Korean: return "한국인"
        case .German: return "Deutsch"
        case .Italian: return "Italiana"
        case .Japanese: return "日本語"
        case .Indonesian: return "Bahasa Indonesia"
        case .Chinese: return "中文"
        case .hindi: return "हिन्दी"
        }
    }
    
    // ADD THIS - FLAG EMOJI
//       var flagEmoji: String {
//           switch self {
//           case .english: return "🇬🇧"
//           case .spanish: return "🇪🇸"
//           case .french: return "🇫🇷"
//           case .portuguese: return "🇵🇹"
//           case .russian: return "🇷🇺"
//           case .Korean: return "🇰🇷"
//           case .German: return "🇩🇪"
//           case .Italian: return "🇮🇹"
//           case .Japanese: return "🇯🇵"
//           case .Indonesian: return "🇮🇩"
//           case .Chinese: return "🇨🇳"
//           case .hindi: return "🇮🇳"
//           }
//       }
    
    var flagImageName: String {
        switch self {
        case .english: return "flag_en"
        case .spanish: return "flag_es"
        case .french: return "flag_fr"
        case .portuguese: return "flag_pt"
        case .russian: return "flag_ru"
        case .Korean: return "flag_ko"
        case .German: return "flag_de"
        case .Italian: return "flag_it"
        case .Japanese: return "flag_ja"
        case .Indonesian: return "flag_id"
        case .Chinese: return "flag_cn"
        case .hindi: return "flag_in"
        }
    }
    
    var translations: [String: String] {
        switch self {
        case .english:
            return EnglishTranslations.dictionary
        case .spanish:
            return SpanishTranslations.dictionary
        case .french:
            return FrenchTranslations.dictionary
        case .portuguese:
            return PortugueseTranslations.dictionary
        case .russian:
            return RussianTranslations.dictionary
        case .Korean:
            return KoreanTranslations.dictionary
        case .German:
            return GermanTranslations.dictionary
        case .Italian:
            return ItalianTranslations.dictionary
        case .Japanese:
            return JapaneseTranslations.dictionary
        case .Indonesian:
            return IndonesianTranslations.dictionary
        case .Chinese:
            return ChineseTranslations.dictionary
        case .hindi:
            return HindiTranslations.dictionary
        
        }
    }
}

// MARK: - English Translations
struct EnglishTranslations {
    static let dictionary: [String: String] = [
        // Tabs
        "tab.basic": "Basic",
        "tab.scientific": "Scientific",
        "tab.history": "History",
        "tab.convert": "Convert",
        "tab.more": "More",
        "settings.title": "Settings",
        "settings.language": "Language",
        "settings.appearance": "Appearance",
        "settings.theme": "Theme Mode",
        "settings.back": "Back",
        "settings.done": "Done",
        "theme.light": "Light Mode",
        "theme.dark": "Dark Mode",
        "theme.current.light": "Light",
        "theme.current.dark": "Dark",
        "calculator.title": "Calculator",
        "languages": "Languages",
        "history.clear": "Clear All",
        
        
        "history.not": "No History Yet",
        "history.small.not": "your calculations will appear here!",
        "converters": "Converters",
        "length": "Length",
        "weight": "Weight",
        "temperature": "Temperature",
        "volume": "Volume",
        "area": "Area",
        "speed": "Speed",
        "time": "Time",
        "data": "Data",
        "from": "From",
        "to": "To",
        "enter.value": "Enter Value",
        "meters": "Meters",
        "kilometers": "Kilometers",
        "miles": "Miles",
        "feet": "Feet",
        "inches": "Inches",
        "centimeters": "Centimeters",
        "kilograms": "Kilograms",
        "grams": "Grams",
        "pounds": "Pounds",
        "ounces": "Ounces",
        "tons": "Tons",
        "celsius": "Celsius",
        "fahrenheit": "Fahrenheit",
        "kelvin": "Kelvin",
        "liters": "Liters",
        "milliliters": "Milliliters",
        "gallons": "Gallons",
        "cups": "Cups",
        "pints": "pints",
        "sqmeters": "Sq Meters",
        "sqkm": "Sq Km",
        "sqmiles": "Sq Miles",
        "sqfeet": "Sq Feet",
        "acres": "Acres",
        "m/s": "m/s",
        "km/h": "km/h",
        "mph": "mph",
        "knots": "knots",
        "seconds": "Seconds",
        "minutes": "Minutes",
        "hours": "Hours",
        "weeks": "Weeks",
        "bytes": "Bytes",
        "kb": "KB",
        "mb": "MB",
        "gb": "GB",
        "tb": "TB",
        "moretools": "More Tools",
        "tip.calculator": "Tip Calculator",
        "age.calculator": "Age Calculator",
        "discount.calculator": "Discount Calculator",
        "loan.calculator": "Loan Calaculator",
        "bill.amount": "Bill Amount",
        "tip.percentage":  "Tip Percentage",
        "split.between": "Split Between",
        "tip.amount": "Tip Amount",
        "total.amount": "Total Amount",
        "per.person": "Per Person",
        "select.dob": "Select Your Birth Date",
        "years": "Years",
        "months": "Months",
        "days": "Days",
        "total.months": "Total Months",
        "total.weeks": "Total Weeks",
        "total.days": "Total Days",
        "original.price": "Original Price",
        "discount": "Discount",
        "discount.amount": "Discount Amount",
        "final.price": "Final Price",
        "loan.amount": "Loan Amount",
        "interest.rate": "Interest Rate (% per year)",
        "loan.term": "Loan Term (months)",
        "month.payment": "Monthly Payment",
        "total.payment": "Total Payment",
        "total.interest":"Total Interest",
        "person": "Person",
        "people": "People",
        "select.currency": "Select Currency",
        "currency": "Currency",
        "data.storage": "Data Storage",
        "restore.purchase": "Restore Purchases",
        "privacy.policy": "Privacy Policy",
        "terms.of.use": "Terms of Use",
        "manage.subscription": "Manage Subscription",
        "subscribe.now": "Subscribe Now",
        "remove.ads": "Remove Ads & Export Loan Report (PDF)"
        
    ]
}

struct SpanishTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "Básica",
        "tab.scientific": "científica",
        "tab.history": "historia",
        "tab.convert": "convertir",
        "tab.more": "más",
        "settings.title": "ajustes",
        "settings.language": "idioma",
        "settings.appearance": "Apariencia",
        "settings.theme": "Modo temático",
        "settings.back": "Atrás",
        "settings.done": "Hecho",
        "theme.light": "Modo de luz",
        "theme.dark": "Modo oscuro",
        "theme.current.light": "Ligera",
        "theme.current.dark": "Oscura",
        "calculator.title": "Calculadora",
        "languages": "Idiomas",
        "history.clear": "Borrar todo",
        
        
        "history.not": "Sin historial aún",
        "history.small.not": "¡Tus cálculos aparecerán aquí!",
        "converters": "Convertidores",
        "length": "Longitud",
        "weight": "Peso",
        "temperature": "Temperatura",
        "volume": "Volumen",
        "area": "Área",
        "speed": "Velocidad",
        "time": "Tiempo",
        "data": "Datos",
        "from": "De",
        "to": "A",
        "enter.value": "Ingresar valor",
        "meters": "Metros",
        "kilometers": "Kilómetros",
        "miles": "Millas",
        "feet": "Pies",
        "inches": "Pulgadas",
        "centimeters": "Centímetros",
        "kilograms": "Kilogramos",
        "grams": "Gramos",
        "pounds": "Libras",
        "ounces": "Onzas",
        "tons": "Toneladas",
        "celsius": "Celsius",
        "fahrenheit": "Fahrenheit",
        "kelvin": "Kelvin",
        "liters": "Litros",
        "milliliters": "Mililitros",
        "gallons": "Galones",
        "cups": "Tazas",
        "pints": "Pintas",
        "sqmeters": "Metros cuadrados",
        "sqkm": "Kilómetros cuadrados",
        "sqmiles": "Millas cuadradas",
        "sqfeet": "Pies cuadrados",
        "acres": "Acres",
        "m/s": "m/s",
        "km/h": "km/h",
        "mph": "mph",
        "knots": "Nudos",
        "seconds": "Segundos",
        "minutes": "Minutos",
        "hours": "Horas",
        "weeks": "Semanas",
        "bytes": "Bytes",
        "kb": "KB",
        "mb": "MB",
        "gb": "GB",
        "tb": "TB",
        "moretools": "Más herramientas",
        "tip.calculator": "Calculadora de propinas",
        "age.calculator": "Calculadora de edad",
        "discount.calculator": "Calculadora de descuento",
        "loan.calculator": "Calculadora de préstamos",
        "bill.amount": "Monto de la factura",
        "tip.percentage": "Porcentaje de propina",
        "split.between": "Dividir entre",
        "tip.amount": "Monto de la propina",
        "total.amount": "Monto total",
        "per.person": "Por persona",
        "select.dob": "Selecciona tu fecha de nacimiento",
        "years": "Años",
        "months": "Meses",
        "days": "Días",
        "total.months": "Meses totales",
        "total.weeks": "Semanas totales",
        "total.days": "Días totales",
        "original.price": "Precio original",
        "discount": "Descuento",
        "discount.amount": "Monto del descuento",
        "final.price": "Precio final",
        "loan.amount": "Monto del préstamo",
        "interest.rate": "Tasa de interés (% por año)",
        "loan.term": "Plazo del préstamo (meses)",
        "month.payment": "Pago mensual",
        "total.payment": "Pago total",
        "total.interest": "Interés total",
        "person": "Persona",
        "people": "Personas",
        "select.currency": "Seleccionar moneda",
        "currency": "Moneda",
        "data.storage": "Almacenamiento de datos",
        "restore.purchase": "Restaurar compras",
        "privacy.policy": "política de privacidad",
        "terms.of.use": "Condiciones de uso",
        "manage.subscription": "Administrar suscripción",
        "subscribe.now": "Suscríbete ahora",
        "remove.ads": "Eliminar anuncios y exportar informe de préstamos (PDF)"
    ]
}

struct FrenchTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "Basique",
        "tab.scientific": "Scientifique",
        "tab.history": "Histoire",
        "tab.convert": "Convertir",
        "tab.more": "Plus",
        "settings.title": "paramètres",
        "settings.language": "langue",
        "settings.appearance": "Apparence",
        
        "settings.theme": "Mode Thème",
        "settings.back": "Dos",
        "settings.done": "Fait",
        "theme.light": "Mode lumière",
        "theme.dark": "Mode sombre",
        "theme.current.light": "Lumière",
        "theme.current.dark": "Sombre",
        "calculator.title": "Calculatrice",
        "languages": "Langues",
        "history.clear": "Tout effacer",
        
        
        "history.not": "Aucun historique pour le moment",
        "history.small.not": "Vos calculs apparaîtront ici !",
        "converters": "Convertisseurs",
        "length": "Longueur",
        "weight": "Poids",
        "temperature": "Température",
        "volume": "Volume",
        "area": "Surface",
        "speed": "Vitesse",
        "time": "Temps",
        "data": "Données",
        "from": "De",
        "to": "À",
        "enter.value": "Entrer la valeur",
        "meters": "Mètres",
        "kilometers": "Kilomètres",
        "miles": "Miles",
        "feet": "Pieds",
        "inches": "Pouces",
        "centimeters": "Centimètres",
        "kilograms": "Kilogrammes",
        "grams": "Grammes",
        "pounds": "Livres",
        "ounces": "Onces",
        "tons": "Tonnes",
        "celsius": "Celsius",
        "fahrenheit": "Fahrenheit",
        "kelvin": "Kelvin",
        "liters": "Litres",
        "milliliters": "Millilitres",
        "gallons": "Gallons",
        "cups": "Tasses",
        "pints": "Pintes",
        "sqmeters": "Mètres carrés",
        "sqkm": "Kilomètres carrés",
        "sqmiles": "Miles carrés",
        "sqfeet": "Pieds carrés",
        "acres": "Acres",
        "m/s": "m/s",
        "km/h": "km/h",
        "mph": "mph",
        "knots": "Nœuds",
        "seconds": "Secondes",
        "minutes": "Minutes",
        "hours": "Heures",
        "weeks": "Semaines",
        "bytes": "Octets",
        "kb": "Ko",
        "mb": "Mo",
        "gb": "Go",
        "tb": "To",
        "moretools": "Plus d’outils",
        "tip.calculator": "Calculateur de pourboire",
        "age.calculator": "Calculateur d’âge",
        "discount.calculator": "Calculateur de remise",
        "loan.calculator": "Calculateur de prêt",
        "bill.amount": "Montant de la facture",
        "tip.percentage": "Pourcentage du pourboire",
        "split.between": "Diviser entre",
        "tip.amount": "Montant du pourboire",
        "total.amount": "Montant total",
        "per.person": "Par personne",
        "select.dob": "Sélectionnez votre date de naissance",
        "years": "Ans",
        "months": "Mois",
        "days": "Jours",
        "total.months": "Total des mois",
        "total.weeks": "Total des semaines",
        "total.days": "Total des jours",
        "original.price": "Prix original",
        "discount": "Remise",
        "discount.amount": "Montant de la remise",
        "final.price": "Prix final",
        "loan.amount": "Montant du prêt",
        "interest.rate": "Taux d’intérêt (% par an)",
        "loan.term": "Durée du prêt (mois)",
        "month.payment": "Paiement mensuel",
        "total.payment": "Paiement total",
        "total.interest": "Intérêt total",
        "person": "Personne",
        "people": "Personnes",
        "select.currency": "Sélectionner la devise",
        "currency": "Devise",
        "data.storage": "Stockage de données",
        
        "restore.purchase": "Restaurer les achats",
        "privacy.policy": "politique de confidentialité",
        "terms.of.use": "Conditions d'utilisation",
        "manage.subscription": "Gérer l'abonnement",
        "subscribe.now": "Abonnez-vous maintenant",
        "remove.ads": "Supprimer les publicités et exporter le rapport de prêt (PDF)"

    ]
}

struct PortugueseTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "Básica",
        "tab.scientific": "Científica",
        "tab.history": "História",
        "tab.convert": "Converter",
        "tab.more": "Mais",
        "settings.title": "Configurações",
        "settings.language": "Linguagem",
        "settings.appearance": "Aparência",
        "settings.theme": "Modo Tema",
        "settings.back": "Voltar",
        "settings.done": "Feita",
        "theme.light": "Modo claro",
        "theme.dark": "Modo escuro",
        "theme.current.light": "Luz",
        "theme.current.dark": "Escura",
        "calculator.title": "Calculadora",
        "languages": "Idiomas",
        "history.clear": "Limpar tudo",
        
        "history.not": "Sem histórico ainda",
        "history.small.not": "Seus cálculos aparecerão aqui!",
        "converters": "Conversores",
        "length": "Comprimento",
        "weight": "Peso",
        "temperature": "Temperatura",
        "volume": "Volume",
        "area": "Área",
        "speed": "Velocidade",
        "time": "Tempo",
        "data": "Dados",
        "from": "De",
        "to": "Para",
        "enter.value": "Digite o valor",
        "meters": "Metros",
        "kilometers": "Quilômetros",
        "miles": "Milhas",
        "feet": "Pés",
        "inches": "Polegadas",
        "centimeters": "Centímetros",
        "kilograms": "Quilogramas",
        "grams": "Gramas",
        "pounds": "Libras",
        "ounces": "Onças",
        "tons": "Toneladas",
        "celsius": "Celsius",
        "fahrenheit": "Fahrenheit",
        "kelvin": "Kelvin",
        "liters": "Litros",
        "milliliters": "Mililitros",
        "gallons": "Galões",
        "cups": "Xícaras",
        "pints": "Pintas",
        "sqmeters": "Metros quadrados",
        "sqkm": "Quilômetros quadrados",
        "sqmiles": "Milhas quadradas",
        "sqfeet": "Pés quadrados",
        "acres": "Acres",
        "m/s": "m/s",
        "km/h": "km/h",
        "mph": "mph",
        "knots": "Nós",
        "seconds": "Segundos",
        "minutes": "Minutos",
        "hours": "Horas",
        "weeks": "Semanas",
        "bytes": "Bytes",
        "kb": "KB",
        "mb": "MB",
        "gb": "GB",
        "tb": "TB",
        "moretools": "Mais ferramentas",
        "tip.calculator": "Calculadora de gorjeta",
        "age.calculator": "Calculadora de idade",
        "discount.calculator": "Calculadora de desconto",
        "loan.calculator": "Calculadora de empréstimo",
        "bill.amount": "Valor da conta",
        "tip.percentage": "Porcentagem da gorjeta",
        "split.between": "Dividir entre",
        "tip.amount": "Valor da gorjeta",
        "total.amount": "Valor total",
        "per.person": "Por pessoa",
        "select.dob": "Selecione sua data de nascimento",
        "years": "Anos",
        "months": "Meses",
        "days": "Dias",
        "total.months": "Total de meses",
        "total.weeks": "Total de semanas",
        "total.days": "Total de dias",
        "original.price": "Preço original",
        "discount": "Desconto",
        "discount.amount": "Valor do desconto",
        "final.price": "Preço final",
        "loan.amount": "Valor do empréstimo",
        "interest.rate": "Taxa de juros (% ao ano)",
        "loan.term": "Prazo do empréstimo (meses)",
        "month.payment": "Pagamento mensal",
        "total.payment": "Pagamento total",
        "total.interest": "Total de juros",
        "person": "Pessoa",
        "people": "Pessoas",
        "select.currency": "Selecionar moeda",
        "currency": "Moeda",
        "data.storage": "Armazenamento de dados",
        
        "restore.purchase": "Restaurar compras",
        "privacy.policy": "política de Privacidade",
        "terms.of.use": "Termos de Uso",
        "manage.subscription": "Gerenciar assinatura",
        "subscribe.now": "Assine agora",
        "remove.ads": "Remover anúncios e exportar relatório de empréstimo (PDF)"

    ]
}

struct RussianTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "Базовый",
        "tab.scientific": "Научный",
        "tab.history": "История",
        "tab.convert": "Конвертировать",
        "tab.more": "Более",
        "settings.title": "Настройки",
        "settings.language": "Язык",
        "settings.appearance": "Появление",
        "settings.theme": "Тематический режим",
        "settings.back": "Назад",
        "settings.done": "Сделанный",
        "theme.light": "Светлый режим",
        "theme.dark": "Темный режим",
        "theme.current.light": "Свет",
        "theme.current.dark": "Темный",
        "calculator.title": "Калькулятор",
        "languages": "Языки",
        "history.clear": "Очистить все",
        
        "history.not": "Истории пока нет",
        "history.small.not": "Ваши вычисления появятся здесь!",
        "converters": "Конвертеры",
        "length": "Длина",
        "weight": "Вес",
        "temperature": "Температура",
        "volume": "Объём",
        "area": "Площадь",
        "speed": "Скорость",
        "time": "Время",
        "data": "Данные",
        "from": "Из",
        "to": "В",
        "enter.value": "Введите значение",
        "meters": "Метры",
        "kilometers": "Километры",
        "miles": "Мили",
        "feet": "Футы",
        "inches": "Дюймы",
        "centimeters": "Сантиметры",
        "kilograms": "Килограммы",
        "grams": "Граммы",
        "pounds": "Фунты",
        "ounces": "Унции",
        "tons": "Тонны",
        "celsius": "Цельсий",
        "fahrenheit": "Фаренгейт",
        "kelvin": "Кельвин",
        "liters": "Литры",
        "milliliters": "Миллилитры",
        "gallons": "Галлоны",
        "cups": "Чашки",
        "pints": "Пинты",
        "sqmeters": "Кв. метры",
        "sqkm": "Кв. километры",
        "sqmiles": "Кв. мили",
        "sqfeet": "Кв. футы",
        "acres": "Акры",
        "m/s": "м/с",
        "km/h": "км/ч",
        "mph": "миль/ч",
        "knots": "Узлы",
        "seconds": "Секунды",
        "minutes": "Минуты",
        "hours": "Часы",
        "weeks": "Недели",
        "bytes": "Байты",
        "kb": "КБ",
        "mb": "МБ",
        "gb": "ГБ",
        "tb": "ТБ",
        "moretools": "Больше инструментов",
        "tip.calculator": "Калькулятор чаевых",
        "age.calculator": "Калькулятор возраста",
        "discount.calculator": "Калькулятор скидки",
        "loan.calculator": "Калькулятор кредита",
        "bill.amount": "Сумма счета",
        "tip.percentage": "Процент чаевых",
        "split.between": "Разделить между",
        "tip.amount": "Сумма чаевых",
        "total.amount": "Итоговая сумма",
        "per.person": "На человека",
        "select.dob": "Выберите дату рождения",
        "years": "Годы",
        "months": "Месяцы",
        "days": "Дни",
        "total.months": "Всего месяцев",
        "total.weeks": "Всего недель",
        "total.days": "Всего дней",
        "original.price": "Исходная цена",
        "discount": "Скидка",
        "discount.amount": "Сумма скидки",
        "final.price": "Итоговая цена",
        "loan.amount": "Сумма кредита",
        "interest.rate": "Процентная ставка (% в год)",
        "loan.term": "Срок кредита (месяцы)",
        "month.payment": "Ежемесячный платеж",
        "total.payment": "Общий платеж",
        "total.interest": "Общие проценты",
        "person": "Человек",
        "people": "Люди",
        "select.currency": "Выберите валюту",
        "currency": "Валюта",
        "data.storage": "Хранение данных",
        
        "restore.purchase": "Восстановить покупки",
        "privacy.policy": "политика конфиденциальности",
        "terms.of.use": "Условия эксплуатации",
        "manage.subscription": "Управление подпиской",
        "subscribe.now": "Подпишитесь сейчас",
        "remove.ads": "Удалить рекламу и экспортировать отчет о кредите (PDF)"

    ]
}

struct KoreanTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "기초적인",
        "tab.scientific": "과학적",
        "tab.history": "역사",
        "tab.convert": "전환하다",
        "tab.more": "더",
        "settings.title": "설정",
        "settings.language": "언어",
        "settings.appearance": "모습",
        "settings.theme": "테마 모드",
        "settings.back": "뒤쪽에",
        "settings.done": "완료",
        "theme.light": "라이트 모드",
        "theme.dark": "다크 모드",
        "theme.current.light": "빛",
        "theme.current.dark": "어두운",
        "calculator.title": "계산자",
        "languages": "언어",
        "history.clear": "모두 지우기",
        
        "history.not": "아직 기록이 없습니다",
        "history.small.not": "계산 결과가 여기에 표시됩니다!",
        "converters": "변환기",
        "length": "길이",
        "weight": "무게",
        "temperature": "온도",
        "volume": "부피",
        "area": "면적",
        "speed": "속도",
        "time": "시간",
        "data": "데이터",
        "from": "에서",
        "to": "으로",
        "enter.value": "값 입력",
        "meters": "미터",
        "kilometers": "킬로미터",
        "miles": "마일",
        "feet": "피트",
        "inches": "인치",
        "centimeters": "센티미터",
        "kilograms": "킬로그램",
        "grams": "그램",
        "pounds": "파운드",
        "ounces": "온스",
        "tons": "톤",
        "celsius": "섭씨",
        "fahrenheit": "화씨",
        "kelvin": "켈빈",
        "liters": "리터",
        "milliliters": "밀리리터",
        "gallons": "갤런",
        "cups": "컵",
        "pints": "파인트",
        "sqmeters": "제곱미터",
        "sqkm": "제곱킬로미터",
        "sqmiles": "제곱마일",
        "sqfeet": "제곱피트",
        "acres": "에이커",
        "m/s": "미터/초",
        "km/h": "킬로미터/시",
        "mph": "마일/시",
        "knots": "노트",
        "seconds": "초",
        "minutes": "분",
        "hours": "시간",
        "weeks": "주",
        "bytes": "바이트",
        "kb": "킬로바이트",
        "mb": "메가바이트",
        "gb": "기가바이트",
        "tb": "테라바이트",
        "moretools": "더 많은 도구",
        "tip.calculator": "팁 계산기",
        "age.calculator": "나이 계산기",
        "discount.calculator": "할인 계산기",
        "loan.calculator": "대출 계산기",
        "bill.amount": "청구 금액",
        "tip.percentage": "팁 비율",
        "split.between": "나누기",
        "tip.amount": "팁 금액",
        "total.amount": "총 금액",
        "per.person": "1인당",
        "select.dob": "생년월일 선택",
        "years": "년",
        "months": "개월",
        "days": "일",
        "total.months": "총 개월 수",
        "total.weeks": "총 주 수",
        "total.days": "총 일 수",
        "original.price": "원래 가격",
        "discount": "할인",
        "discount.amount": "할인 금액",
        "final.price": "최종 가격",
        "loan.amount": "대출 금액",
        "interest.rate": "이자율 (% / 년)",
        "loan.term": "대출 기간 (개월)",
        "month.payment": "월별 상환금",
        "total.payment": "총 상환금",
        "total.interest": "총 이자",
        "person": "명",
        "people": "명",
        "select.currency": "통화 선택",
        "currency": "통화",
        "data.storage": "데이터 저장소",
        
        "restore.purchase": "구매 복원",
        "privacy.policy": "개인 정보 보호 정책",
        "terms.of.use": "이용약관",
        "manage.subscription": "구독 관리",
        "subscribe.now": "지금 구독하세요",
        "remove.ads": "광고 제거 및 대출 보고서 내보내기 (PDF)"

    ]
}

struct GermanTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "Basic",
        "tab.scientific": "Wissenschaftlich",
        "tab.history": "Geschichte",
        "tab.convert": "Konvertieren",
        "tab.more": "Mehr",
        "settings.title": "Einstellungen",
        "settings.language": "Sprache",
        "settings.appearance": "Aussehen",
        "settings.theme": "Themenmodus",
        "settings.back": "Zurück",
        "settings.done": "Erledigt",
        "theme.light": "Lichtmodus",
        "theme.dark": "Dunkler Modus",
        "theme.current.light": "Licht",
        "theme.current.dark": "Dunkel",
        "calculator.title": "Kalkulator",
        "languages": "Sprachen",
        "history.clear": "Alles löschen",
        
        "history.not": "Noch kein Verlauf",
        "history.small.not": "Ihre Berechnungen werden hier angezeigt!",
        "converters": "Konverter",
        "length": "Länge",
        "weight": "Gewicht",
        "temperature": "Temperatur",
        "volume": "Volumen",
        "area": "Fläche",
        "speed": "Geschwindigkeit",
        "time": "Zeit",
        "data": "Daten",
        "from": "Von",
        "to": "Nach",
        "enter.value": "Wert eingeben",
        "meters": "Meter",
        "kilometers": "Kilometer",
        "miles": "Meilen",
        "feet": "Fuß",
        "inches": "Zoll",
        "centimeters": "Zentimeter",
        "kilograms": "Kilogramm",
        "grams": "Gramm",
        "pounds": "Pfund",
        "ounces": "Unzen",
        "tons": "Tonnen",
        "celsius": "Celsius",
        "fahrenheit": "Fahrenheit",
        "kelvin": "Kelvin",
        "liters": "Liter",
        "milliliters": "Milliliter",
        "gallons": "Gallonen",
        "cups": "Tassen",
        "pints": "Pinten",
        "sqmeters": "Quadratmeter",
        "sqkm": "Quadratkilometer",
        "sqmiles": "Quadratmeilen",
        "sqfeet": "Quadratfuß",
        "acres": "Morgen",
        "m/s": "m/s",
        "km/h": "km/h",
        "mph": "mph",
        "knots": "Knoten",
        "seconds": "Sekunden",
        "minutes": "Minuten",
        "hours": "Stunden",
        "weeks": "Wochen",
        "bytes": "Bytes",
        "kb": "KB",
        "mb": "MB",
        "gb": "GB",
        "tb": "TB",
        "moretools": "Weitere Werkzeuge",
        "tip.calculator": "Trinkgeldrechner",
        "age.calculator": "Altersrechner",
        "discount.calculator": "Rabattrechner",
        "loan.calculator": "Darlehensrechner",
        "bill.amount": "Rechnungsbetrag",
        "tip.percentage": "Trinkgeldprozentsatz",
        "split.between": "Aufteilen zwischen",
        "tip.amount": "Trinkgeldbetrag",
        "total.amount": "Gesamtbetrag",
        "per.person": "Pro Person",
        "select.dob": "Geburtsdatum auswählen",
        "years": "Jahre",
        "months": "Monate",
        "days": "Tage",
        "total.months": "Monate gesamt",
        "total.weeks": "Wochen gesamt",
        "total.days": "Tage gesamt",
        "original.price": "Originalpreis",
        "discount": "Rabatt",
        "discount.amount": "Rabattbetrag",
        "final.price": "Endpreis",
        "loan.amount": "Darlehensbetrag",
        "interest.rate": "Zinssatz (% pro Jahr)",
        "loan.term": "Laufzeit (Monate)",
        "month.payment": "Monatliche Zahlung",
        "total.payment": "Gesamtzahlung",
        "total.interest": "Gesamtzinsen",
        "person": "Person",
        "people": "Personen",
        "select.currency": "Währung auswählen",
        "currency": "Währung",
        "data.storage": "Datenspeicher",
        
        "restore.purchase": "Einkäufe wiederherstellen",
        "privacy.policy": "Datenschutzrichtlinie",
        "terms.of.use": "Nutzungsbedingungen",
        "manage.subscription": "Abonnement verwalten",
        "subscribe.now": "Jetzt abonnieren",
        "remove.ads": "Anzeigen entfernen & Kreditbericht exportieren (PDF)"

    ]
}

struct ItalianTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "Di base",
        "tab.scientific": "Scientifica",
        "tab.history": "Storia",
        "tab.convert": "Convertire",
        "tab.more": "Di più",
        "settings.title": "Impostazioni",
        "settings.language": "Lingua",
        "settings.appearance": "Aspetto",
        "settings.theme": "Modalità tema",
        "settings.back": "Indietro",
        "settings.done": "Fatto",
        "theme.light": "Modalità luce",
        "theme.dark": "Modalità oscura",
        "theme.current.light": "Leggera",
        "theme.current.dark": "Buia",
        "calculator.title": "Calcolatrice",
        "languages": "Lingue",
        "history.clear": "Cancella tutto",
        
        "history.not": "Nessuna cronologia ancora",
        "history.small.not": "I tuoi calcoli appariranno qui!",
        "converters": "Convertitori",
        "length": "Lunghezza",
        "weight": "Peso",
        "temperature": "Temperatura",
        "volume": "Volume",
        "area": "Area",
        "speed": "Velocità",
        "time": "Tempo",
        "data": "Dati",
        "from": "Da",
        "to": "A",
        "enter.value": "Inserisci valore",
        "meters": "Metri",
        "kilometers": "Chilometri",
        "miles": "Miglia",
        "feet": "Piedi",
        "inches": "Pollici",
        "centimeters": "Centimetri",
        "kilograms": "Chilogrammi",
        "grams": "Grammi",
        "pounds": "Libbre",
        "ounces": "Once",
        "tons": "Tonnellate",
        "celsius": "Celsius",
        "fahrenheit": "Fahrenheit",
        "kelvin": "Kelvin",
        "liters": "Litri",
        "milliliters": "Millilitri",
        "gallons": "Galloni",
        "cups": "Tazze",
        "pints": "Pinte",
        "sqmeters": "Metri quadrati",
        "sqkm": "Chilometri quadrati",
        "sqmiles": "Miglia quadrate",
        "sqfeet": "Piedi quadrati",
        "acres": "Acri",
        "m/s": "m/s",
        "km/h": "km/h",
        "mph": "mph",
        "knots": "Nodi",
        "seconds": "Secondi",
        "minutes": "Minuti",
        "hours": "Ore",
        "weeks": "Settimane",
        "bytes": "Byte",
        "kb": "KB",
        "mb": "MB",
        "gb": "GB",
        "tb": "TB",
        "moretools": "Altri strumenti",
        "tip.calculator": "Calcolatore di mancia",
        "age.calculator": "Calcolatore di età",
        "discount.calculator": "Calcolatore di sconto",
        "loan.calculator": "Calcolatore di prestito",
        "bill.amount": "Importo del conto",
        "tip.percentage": "Percentuale di mancia",
        "split.between": "Dividi tra",
        "tip.amount": "Importo della mancia",
        "total.amount": "Importo totale",
        "per.person": "Per persona",
        "select.dob": "Seleziona la tua data di nascita",
        "years": "Anni",
        "months": "Mesi",
        "days": "Giorni",
        "total.months": "Totale mesi",
        "total.weeks": "Totale settimane",
        "total.days": "Totale giorni",
        "original.price": "Prezzo originale",
        "discount": "Sconto",
        "discount.amount": "Importo dello sconto",
        "final.price": "Prezzo finale",
        "loan.amount": "Importo del prestito",
        "interest.rate": "Tasso di interesse (% all'anno)",
        "loan.term": "Durata del prestito (mesi)",
        "month.payment": "Pagamento mensile",
        "total.payment": "Pagamento totale",
        "total.interest": "Interessi totali",
        "person": "Persona",
        "people": "Persone",
        "select.currency": "Seleziona valuta",
        "currency": "Valuta",
        "data.storage": "Archiviazione dati",
        
        "restore.purchase": "Restore Purchases",
        "privacy.policy": "Privacy Policy",
        "terms.of.use": "Terms of Use",
        "manage.subscription": "Gestisci abbonamento",
        "subscribe.now": "Iscriviti ora",
        "remove.ads": "Rimuovi annunci ed esporta il report sui prestiti (PDF)"

    ]
}

struct JapaneseTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "基本",
        "tab.scientific": "科学的",
        "tab.history": "歴史",
        "tab.convert": "変換する",
        "tab.more": "もっと",
        "settings.title": "設定",
        "settings.language": "言語",
        "settings.appearance": "外観",
        "settings.theme": "テーマモード",
        "settings.back": "戻る",
        "settings.done": "終わり",
        "theme.light": "ライトモード",
        "theme.dark": "ダークモード",
        "theme.current.light": "ライト",
        "theme.current.dark": "暗い",
        "calculator.title": "電卓",
        "languages": "言語",
        "history.clear": "すべてクリア",
        
        "history.not": "履歴はまだありません",
        "history.small.not": "計算結果がここに表示されます！",
        "converters": "コンバーター",
        "length": "長さ",
        "weight": "重さ",
        "temperature": "温度",
        "volume": "体積",
        "area": "面積",
        "speed": "速度",
        "time": "時間",
        "data": "データ",
        "from": "から",
        "to": "へ",
        "enter.value": "値を入力",
        "meters": "メートル",
        "kilometers": "キロメートル",
        "miles": "マイル",
        "feet": "フィート",
        "inches": "インチ",
        "centimeters": "センチメートル",
        "kilograms": "キログラム",
        "grams": "グラム",
        "pounds": "ポンド",
        "ounces": "オンス",
        "tons": "トン",
        "celsius": "摂氏",
        "fahrenheit": "華氏",
        "kelvin": "ケルビン",
        "liters": "リットル",
        "milliliters": "ミリリットル",
        "gallons": "ガロン",
        "cups": "カップ",
        "pints": "パイント",
        "sqmeters": "平方メートル",
        "sqkm": "平方キロメートル",
        "sqmiles": "平方マイル",
        "sqfeet": "平方フィート",
        "acres": "エーカー",
        "m/s": "m/s",
        "km/h": "km/h",
        "mph": "mph",
        "knots": "ノット",
        "seconds": "秒",
        "minutes": "分",
        "hours": "時間",
        "weeks": "週",
        "bytes": "バイト",
        "kb": "KB",
        "mb": "MB",
        "gb": "GB",
        "tb": "TB",
        "moretools": "その他のツール",
        "tip.calculator": "チップ計算機",
        "age.calculator": "年齢計算機",
        "discount.calculator": "割引計算機",
        "loan.calculator": "ローン計算機",
        "bill.amount": "請求金額",
        "tip.percentage": "チップの割合",
        "split.between": "分割人数",
        "tip.amount": "チップ金額",
        "total.amount": "合計金額",
        "per.person": "1人あたり",
        "select.dob": "生年月日を選択",
        "years": "年",
        "months": "ヶ月",
        "days": "日",
        "total.months": "合計ヶ月",
        "total.weeks": "合計週",
        "total.days": "合計日",
        "original.price": "元の価格",
        "discount": "割引",
        "discount.amount": "割引額",
        "final.price": "最終価格",
        "loan.amount": "ローン金額",
        "interest.rate": "金利（年％）",
        "loan.term": "ローン期間（月）",
        "month.payment": "月々の支払い",
        "total.payment": "総支払額",
        "total.interest": "総利息",
        "person": "人",
        "people": "人",
        "select.currency": "通貨を選択",
        "currency": "通貨",
        "data.storage": "データストレージ",
        "restore.purchase": "購入を復元する",
        "privacy.policy": "プライバシーポリシー",
        "terms.of.use": "利用規約",
        "manage.subscription": "サブスクリプションの管理",
        "subscribe.now": "今すぐ購読する",
        "remove.ads": "広告を削除してローンレポートをエクスポートする（PDF"
    ]
}

struct IndonesianTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "Dasar",
        "tab.scientific": "Ilmiah",
        "tab.history": "Sejarah",
        "tab.convert": "Mengubah",
        "tab.more": "Lagi",
        "settings.title": "Pengaturan",
        "settings.language": "Bahasa",
        "settings.appearance": "Penampilan",
        "settings.theme": "Modus Tema",
        "settings.back": "Kembali",
        "settings.done": "Selesai",
        "theme.light": "Modus Cahaya",
        "theme.dark": "Mode Gelap",
        "theme.current.light": "Lampu",
        "theme.current.dark": "Gelap",
        "calculator.title": "Kalkulator",
        "languages": "Bahasa",
        "history.clear": "Hapus Semua",
        
        "history.not": "Belum ada riwayat",
        "history.small.not": "Perhitungan Anda akan muncul di sini!",
        "converters": "Konverter",
        "length": "Panjang",
        "weight": "Berat",
        "temperature": "Suhu",
        "volume": "Volume",
        "area": "Luas",
        "speed": "Kecepatan",
        "time": "Waktu",
        "data": "Data",
        "from": "Dari",
        "to": "Ke",
        "enter.value": "Masukkan nilai",
        "meters": "Meter",
        "kilometers": "Kilometer",
        "miles": "Mil",
        "feet": "Kaki",
        "inches": "Inci",
        "centimeters": "Sentimeter",
        "kilograms": "Kilogram",
        "grams": "Gram",
        "pounds": "Pound",
        "ounces": "Ons",
        "tons": "Ton",
        "celsius": "Celsius",
        "fahrenheit": "Fahrenheit",
        "kelvin": "Kelvin",
        "liters": "Liter",
        "milliliters": "Mililiter",
        "gallons": "Galon",
        "cups": "Cangkir",
        "pints": "Pint",
        "sqmeters": "Meter persegi",
        "sqkm": "Kilometer persegi",
        "sqmiles": "Mil persegi",
        "sqfeet": "Kaki persegi",
        "acres": "Acre",
        "m/s": "m/s",
        "km/h": "km/j",
        "mph": "mph",
        "knots": "Knot",
        "seconds": "Detik",
        "minutes": "Menit",
        "hours": "Jam",
        "weeks": "Minggu",
        "bytes": "Byte",
        "kb": "KB",
        "mb": "MB",
        "gb": "GB",
        "tb": "TB",
        "moretools": "Alat lainnya",
        "tip.calculator": "Kalkulator tip",
        "age.calculator": "Kalkulator usia",
        "discount.calculator": "Kalkulator diskon",
        "loan.calculator": "Kalkulator pinjaman",
        "bill.amount": "Jumlah tagihan",
        "tip.percentage": "Persentase tip",
        "split.between": "Bagi antara",
        "tip.amount": "Jumlah tip",
        "total.amount": "Jumlah total",
        "per.person": "Per orang",
        "select.dob": "Pilih tanggal lahir",
        "years": "Tahun",
        "months": "Bulan",
        "days": "Hari",
        "total.months": "Total bulan",
        "total.weeks": "Total minggu",
        "total.days": "Total hari",
        "original.price": "Harga asli",
        "discount": "Diskon",
        "discount.amount": "Jumlah diskon",
        "final.price": "Harga akhir",
        "loan.amount": "Jumlah pinjaman",
        "interest.rate": "Suku bunga (% per tahun)",
        "loan.term": "Jangka waktu pinjaman (bulan)",
        "month.payment": "Pembayaran bulanan",
        "total.payment": "Total pembayaran",
        "total.interest": "Total bunga",
        "person": "Orang",
        "people": "Orang",
        "select.currency": "Pilih mata uang",
        "currency": "Mata Uang",
        "data.storage": "Penyimpanan Data",
        
       "restore.purchase": "Pulihkan Pembelian",
        "privacy.policy": "Kebijakan Privasi",
        "terms.of.use": "Ketentuan Penggunaan",
        "manage.subscription": "Kelola Langganan",
        "subscribe.now": "Berlangganan Sekarang",
        "remove.ads": "Hapus Iklan & Ekspor Laporan Pinjaman (PDF)"

    ]
}

struct ChineseTranslations {
    static let dictionary: [String: String] = [
        "tab.basic": "基本的",
        "tab.scientific": "科学的",
        "tab.history": "历史",
        "tab.convert": "转变",
        "tab.more": "更多的",
        "settings.title": "设置",
        "settings.language": "语言",
        "settings.appearance": "外貌",
        "settings.theme": "主题模式",
        "settings.back": "后退",
        "settings.done": "完毕",
        "theme.light": "灯光模式",
        "theme.dark": "深色模式",
        "theme.current.light": "光",
        "theme.current.dark": "黑暗的",
        "calculator.title": "计算器",
        "languages": "语言",
        "history.clear": "全部清除",
        
        "history.not": "暂无历史记录",
        "history.small.not": "您的计算结果将显示在这里！",
        "converters": "转换器",
        "length": "长度",
        "weight": "重量",
        "temperature": "温度",
        "volume": "体积",
        "area": "面积",
        "speed": "速度",
        "time": "时间",
        "data": "数据",
        "from": "从",
        "to": "到",
        "enter.value": "输入数值",
        "meters": "米",
        "kilometers": "公里",
        "miles": "英里",
        "feet": "英尺",
        "inches": "英寸",
        "centimeters": "厘米",
        "kilograms": "千克",
        "grams": "克",
        "pounds": "磅",
        "ounces": "盎司",
        "tons": "吨",
        "celsius": "摄氏度",
        "fahrenheit": "华氏度",
        "kelvin": "开尔文",
        "liters": "升",
        "milliliters": "毫升",
        "gallons": "加仑",
        "cups": "杯",
        "pints": "品脱",
        "sqmeters": "平方米",
        "sqkm": "平方公里",
        "sqmiles": "平方英里",
        "sqfeet": "平方英尺",
        "acres": "英亩",
        "m/s": "米/秒",
        "km/h": "公里/小时",
        "mph": "英里/小时",
        "knots": "节",
        "seconds": "秒",
        "minutes": "分钟",
        "hours": "小时",
        "weeks": "周",
        "bytes": "字节",
        "kb": "KB",
        "mb": "MB",
        "gb": "GB",
        "tb": "TB",
        "moretools": "更多工具",
        "tip.calculator": "小费计算器",
        "age.calculator": "年龄计算器",
        "discount.calculator": "折扣计算器",
        "loan.calculator": "贷款计算器",
        "bill.amount": "账单金额",
        "tip.percentage": "小费比例",
        "split.between": "分摊人数",
        "tip.amount": "小费金额",
        "total.amount": "总金额",
        "per.person": "每人",
        "select.dob": "选择您的出生日期",
        "years": "年",
        "months": "个月",
        "days": "天",
        "total.months": "总月数",
        "total.weeks": "总周数",
        "total.days": "总天数",
        "original.price": "原价",
        "discount": "折扣",
        "discount.amount": "折扣金额",
        "final.price": "最终价格",
        "loan.amount": "贷款金额",
        "interest.rate": "年利率 (%)",
        "loan.term": "贷款期限（月）",
        "month.payment": "每月还款",
        "total.payment": "总还款",
        "total.interest": "总利息",
        "person": "人",
        "people": "人",
        "select.currency": "选择货币",
        "currency": "货币",
        "data.storage": "数据存储",
        
        "restore.purchase": "恢复购买",
        "privacy.policy": "隐私政策",
        "terms.of.use": "使用条款",
        "manage.subscription": "管理订阅",
        "subscribe.now": "立即订阅",
        "remove.ads": "移除广告并导出贷款报告（PDF）"
    ]
}

// MARK: - Hindi Translations
struct HindiTranslations {
    static let dictionary: [String: String] = [
        // Tabs
        "tab.basic": "बेसिक",
        "tab.scientific": "साइंटिफिक",
        "tab.history": "इतिहास",
        "tab.convert": "कन्वर्ट",
        "tab.more": "अधिक",
        "settings.title": "सेटिंग्स",
        "settings.language": "भाषा",
        "settings.appearance": "दिखावट",
        "settings.theme": "थीम मोड",
        "settings.back": "वापस",
        "settings.done": "हो गया",
        "theme.light": "लाइट मोड",
        "theme.dark": "डार्क मोड",
        "theme.current.light": "लाइट",
        "theme.current.dark": "डार्क",
        "calculator.title": "कैलकुलेटर",
        "languages": "भाषाएँ",
        "history.clear": "सभी साफ करें",
        "history.not": "अभी तक कोई इतिहास नहीं",
        "history.small.not": "आपकी गणनाएँ यहाँ दिखाई देंगी!",
        "converters": "कन्वर्टर्स",
        "length": "लंबाई",
        "weight": "वज़न",
        "temperature": "तापमान",
        "volume": "आयतन",
        "area": "क्षेत्र",
        "speed": "रफ़्तार",
        "time": "समय",
        "data": "डेटा",
        "from": "से",
        "to": "तक",
        "enter.value": "मान दर्ज करें",
        "meters": "मीटर",
        "kilometers": "किलोमीटर",
        "miles": "मील",
        "feet": "फीट",
        "inches": "इंच",
        "centimeters": "सेंटीमीटर",
        "kilograms": "किलोग्राम",
        "grams": "ग्राम",
        "pounds": "पाउंड",
        "ounces": "औंस",
        "tons": "टन",
        "celsius": "सेल्सीयस",
        "fahrenheit": "फ़ारेनहाइट",
        "kelvin": "केल्विन",
        "liters": "लीटर",
        "milliliters": "मिलीलीटर",
        "gallons": "गैलन",
        "cups": "कप",
        "pints": "पिंट",
        "sqmeters": "वर्ग मीटर",
        "sqkm": "वर्ग कि.मी",
        "sqmiles": "वर्ग मील",
        "sqfeet": "वर्ग फुट",
        "acres": "एकड़",
        "m/s": "एम/एस",
        "km/h": "किमी/घंटा",
        "mph": "मील प्रति घंटा",
        "knots": "समुद्री मील",
        "seconds": "सेकंड",
        "minutes": "मिनट",
        "hours": "घंटे",
        "days": "दिन",
        "weeks": "हफ्तों",
        "bytes": "बाइट्स",
        "kb": "के.बी",
        "mb": "एम.बी",
        "gb": "जी.बी",
        "tb": "टी.बी",
        "moretools": "अधिक उपकरण",
        "tip.calculator": "टिप कैलकुलेटर",
        "age.calculator": "आयु कैलकुलेटर",
        "discount.calculator": "डिस्काउंट कैलकुलेटर",
        "loan.calculator": "ऋण कैलकुलेटर",
        
        
        "bill.amount": "बिल राशि",
        "tip.percentage":  "टिप प्रतिशत",
        "split.between": "बीच में बाँटना",
        "tip.amount": "टिप राशि",
        "total.amount": "कुल राशि",
        "per.person": "प्रति व्यक्ति",
        "select.dob": "अपनी जन्मतिथि चुनें",
        "years": "साल",
        "months": "महीने",
        "total.months": "कुल माह",
        "total.weeks": "कुल सप्ताह",
        "total.days": "कुल दिन",
        "original.price": "असली कीमत",
        "discount": "छूट",
        "discount.amount": "छूट राशि",
        "final.price": "अंतिम कीमत",
        "loan.amount": "ऋण राशि",
        "interest.rate": "ब्याज दर (प्रति वर्ष %)",
        "loan.term": "ऋण की अवधि (महीनों में)",
        "month.payment": "मासिक भुगतान",
        "total.payment": "कुल भुगतान",
        "total.interest":"कुल ब्याज",
        "person": "व्यक्ति",
        "people": "व्यक्ति",
        "select.currency": "मुद्रा चुनें",
        "currency": "मुद्रा",
        "data.storage": "डेटा संग्रहण",
        
        "restore.purchase": "खरीदारी वापस लौटाएं",
        "privacy.policy": "गोपनीयता नीति",
        "terms.of.use": "उपयोग की शर्तें",
        "manage.subscription": "सदस्यता प्रबंधित करें",
        "subscribe.now": "अब सदस्यता लें",
        "remove.ads": "विज्ञापन हटाएं और ऋण रिपोर्ट निर्यात करें (पीडीएफ)"
    ]
}


// MARK: - String Extension for easy translation
extension String {
    func localized(_ localizationManager: LocalizationManager) -> String {
        return localizationManager.translate(self)
    }
}
